version: '3'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    build:
      context: ./
      dockerfile: Dockerfile

    image: osrf:melodic-desktop-full
    networks:
      - ros
    command: /bin/bash
    restart: always

  # talker:
  #   image: ros:melodic-ros-core
  #   depends_on:
  #     - ros-master
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"
  #     - "ROS_HOSTNAME=talker"
  #   command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
  #   networks:
  #     - ros
  #   restart: always

  # listener:
  #   image: ros:melodic-ros-core
  #   depends_on:
  #     - ros-master
  #   environment:
  #     - "ROS_MASTER_URI=http://ros-master:11311"
  #     - "ROS_HOSTNAME=listener"
  #   command: stdbuf -o L rostopic echo /chatter
  #   networks:
  #     - ros
  #   restart: always